apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # Doesn't expose it to the external world. Will not be reachable from outside. Only from inside the cluster this service can be reached
  type: ClusterIP
  ports:
  - protocol: 'TCP'
    port: 80
    targetPort: 80